#!/usr/bin/env bash

cd "$(tmux display-message -p "#{pane_current_path}")"
url=$(git remote get-url origin)

# no TLD for gitlab to include self-managed instances
if [[ $url == *github.com* || $url == *gitlab* ]]; then
  # ssh url
  if [[ $url == git@* ]]; then
    url="${url#git@}"
    url="${url/:/\/}"
    url="https://$url"
  fi
  (xdg-open "$url" &>/dev/null &)
else
  echo "This repository is not hosted on GitHub"
fi
