#!/bin/bash

DIRS=(
  "$HOME/Documents"
  "$HOME/Documents/notes"
  "$HOME/dev"
  "$HOME/repos"
  "$HOME/"
)

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(fd . "${DIRS[@]}" --type=directory --min-depth=1 --max-depth=1 |
    sed "s|^$HOME/||" | # remove base url from directory paths
    fzf)

  [[ $selected ]] && selected="$HOME/$selected"
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t "$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
  tmux select-window -t "$selected_name:1"
fi

tmux switch-client -t "$selected_name"
